name: API RAZZIES ACTIONS - CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read   # Necessário para acessar o código
      packages: write  # Necessário para publicar pacotes (imagens Docker)
      id-token: write  # Necessário para acessar o GitHub Container Registry (GHCR)

    steps:
      # Checkout do código
      - name: Checkout do código
        uses: actions/checkout@v3

      # Configurar o JDK (Java 21)
      - name: Configurar JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      # Construir e testar o projeto com Maven
      - name: Construir e testar com Maven
        run: mvn clean install

      # Configurar Docker usando a ação oficial
      - name: Configurar Docker
        uses: docker/setup-buildx-action@v2
        with:
          version: latest

      # Construir a imagem Docker
      - name: Build Docker image
        run: |
          docker build -t razzies-action-app .

      # Tag Docker image com "latest"
      - name: Tag Docker image with "latest"
        run: |
          docker tag razzies-action-app ghcr.io/alonsodecarli/razzies-action-app:latest

      # Login no GitHub Container Registry (GHCR)
      - name: Login no GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Fazer push da imagem Docker com a tag "latest"
      - name: Push Docker image to GHCR
        run: |
          docker push ghcr.io/alonsodecarli/razzies-action-app:latest
